################################
# package App::WADTools::Error #
################################
package App::WADTools::Error;

=head1 App::WADTools::Error

Object used to return success/error status to other objects for a given method
call.

=cut

use Moo;

=head2 Attributes

=over

=item error_msg

The error message generated by a method call.  Can be set/reset after the
object is created by:

 $obj->error_msg(q(This is a fine new error message!));

=cut

has q(error_msg) => (
    is  => q(rw),
);

=item content_block

The raw content block received from the C<idGames API Server> that caused the
error.

=cut

has q(content_block) => (
    is => q(rw),
);

=back

=head2 Methods

=over

=item BUILD() (aka 'new')

Creates the L<App::WADTools::Error> object, pass with C<error_msg> and
C<content_block> in order to populate those attributes, or populate those
attributes once the C<Error> object has been created.

=cut

1;
