###################################
# package App::idgasmTools::Error #
###################################
package App::idgasmTools::Error;

=head1 App::idgasmTools::Error

Object used to return success/error status to other objects for a given method
call.

=cut

use Moo;

=head2 Attributes

=over

=item error_msg

The error message generated by a method call.  Can be set/reset after the
object is created by:

 $obj->error_msg(q(This is a fine new error message!));

=cut

has q(error_msg) => (
    is  => q(rw),
);

=back

=head2 Methods

=over

=item BUILD() (aka 'new')

Creates the L<App::idgasmTools::Error> object, optionally with an error
message.

=cut

1;
